#!/usr/bin/env python3
"""Report generator for the SAM2026 paper (MSL only).

Queries the SAM2026 pipeline databases (locally by default, or remotely
over SSH when ``USE_REMOTE=1``), computes statistics for the Modelica
Standard Library (MSL), updates ``papers/SAM2026/variables.tex``,
generates the step2 timeline figure under ``papers/SAM2026/figs/``,
and prints a per-category failure breakdown.

Scope: this script intentionally only reports on the ``MSL`` source.
Other sources (Buildings, ThermofluidStream, ...) may exist in the
database but are skipped.

Variables produced: exactly the 44 ``\\Mb...`` macros referenced from
``papers/SAM2026/body.tex``. Alias macros in ``variables.tex`` (e.g.
``\\MbListProcessedCommits``) are intentionally not generated -- they
delegate to other macros at LaTeX expansion time.

Usage:
    python3 reports.py                # full run
    python3 reports.py --figure-only  # only regenerate the timeline figure

Environment variables (override via shell or ``.env``):
    USE_REMOTE        1 to read DBs / sizes over SSH instead of locally
    REMOTE_HOST       SSH host alias (required when USE_REMOTE=1)
    REMOTE_BASE       Remote base path containing ``dataset/...``
                      (i.e. the SAM2026 project root on the server)
    LOCAL_SOURCE_DIR  Local path holding MSL git clone for date resolution
                      (defaults to ``code/SAM2026/source``)
"""
from __future__ import annotations

import csv
import io
import os
import re
import subprocess
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from statistics import mean

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SAM2026_ROOT = Path(__file__).resolve().parent                # code/SAM2026
REPO_ROOT = SAM2026_ROOT.parent.parent                         # workspace root
PAPER_DIR = REPO_ROOT / "papers" / "SAM2026"
VARIABLES_TEX = PAPER_DIR / "variables.tex"
FIG_DIR = PAPER_DIR / "figs"

DATASET_DIR = SAM2026_ROOT / "dataset"
PIPELINE_DB_LOCAL = str(DATASET_DIR / "pipeline.db")
STEP2_DB_LOCAL = str(DATASET_DIR / "step2_classes.db")
CANONICAL_DIR_LOCAL = str(DATASET_DIR / "canonical_models" / "MSL")

# Load .env if present.
try:
    from dotenv import load_dotenv  # type: ignore
    load_dotenv(SAM2026_ROOT / ".env")
except ImportError:
    pass


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


USE_REMOTE = _env_bool("USE_REMOTE", default=False)
REMOTE_HOST = os.environ.get("REMOTE_HOST", "").strip()
REMOTE_BASE = os.environ.get("REMOTE_BASE", "").strip().rstrip("/")

if USE_REMOTE and (not REMOTE_HOST or not REMOTE_BASE):
    raise RuntimeError(
        "USE_REMOTE=1 requires REMOTE_HOST and REMOTE_BASE to be set "
        "(via environment or code/SAM2026/.env). See .env.example."
    )

PIPELINE_DB_REMOTE = f"{REMOTE_BASE}/dataset/pipeline.db" if REMOTE_BASE else ""
STEP2_DB_REMOTE = f"{REMOTE_BASE}/dataset/step2_classes.db" if REMOTE_BASE else ""
CANONICAL_DIR_REMOTE = f"{REMOTE_BASE}/dataset/canonical_models/MSL" if REMOTE_BASE else ""

ACTIVE_PIPELINE_DB = PIPELINE_DB_REMOTE if USE_REMOTE else PIPELINE_DB_LOCAL
ACTIVE_STEP2_DB = STEP2_DB_REMOTE if USE_REMOTE else STEP2_DB_LOCAL

LOCAL_SOURCE_DIR = Path(
    os.environ.get("LOCAL_SOURCE_DIR", str(SAM2026_ROOT / "source"))
).resolve()

SOURCE_NAME = "MSL"


# ---------------------------------------------------------------------------
# Variables expected in variables.tex (must match body.tex usage).
# Alias macros (\MbListProcessedCommits, \MbCanonInputVersions) are NOT
# generated by the script -- they expand to other macros in LaTeX.
# ---------------------------------------------------------------------------

EXPECTED_VARS = {
    # OMC tool
    "MbToolOmc",
    # Step 1 funnel
    "MbFilterInputCommits", "MbFilterExclBranches", "MbFilterAfterBranches",
    "MbFilterExclPreVThree", "MbFilterAfterPreVThree", "MbFilterExclBot",
    "MbFilterAfterBot", "MbFilterExclNoMo", "MbFilterRetained",
    "MbFilterRetainedPct",
    # Step 2
    "MbListDistinctClassNames", "MbListAllClassVersions",
    "MbListNonExperimentVersions", "MbListNonExperimentPct",
    "MbListExperimentVersions", "MbListExperimentPct",
    "MbListMaxExperimentPerCommit",
    "MbGrowthAllClassMean", "MbGrowthExperimentMean",
    "MbGrowthExperimentRatioMean",
    # Step 3
    "MbCanonCommitsWithExperiment", "MbCanonCommitsWithExperimentPct",
    "MbCanonProducedVersions", "MbCanonProducedPct",
    "MbCanonFailures", "MbCanonFailuresPct",
    # Storage
    "MbStorePipelineDbSize", "MbStoreClassEnumDbSize",
    "MbStoreCanonicalDirSize",
    # Failure breakdown
    "MbFailOperatorRestriction", "MbFailOperatorRestrictionPct",
    "MbFailMissingClass", "MbFailMissingClassPct",
    "MbFailRedeclare", "MbFailRedeclarePct",
    "MbFailMissingBase", "MbFailMissingBasePct",
    "MbFailTimeout", "MbFailTimeoutPct",
    "MbFailPackageLoad", "MbFailPackageLoadPct",
}

# Static values (not computed from the DB).
STATIC_VALUES = {
    "MbToolOmc": "v1.26.3",
}


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------


def _pct(n: int, d: int) -> float:
    return (100.0 * n / d) if d else 0.0


def _fmt_int(n: int) -> str:
    """Format integer with LaTeX-safe thousand separators."""
    return f"{n:,}".replace(",", "{,}")


def _int(s: str) -> int:
    return int((s or "0").replace(",", "").strip() or "0")


# ---------------------------------------------------------------------------
# SQL execution (local sqlite3 CLI or remote over SSH)
# ---------------------------------------------------------------------------


def _run_sql(db_path: str, sql: str, timeout: int = 300) -> list[dict[str, str]]:
    if USE_REMOTE:
        cmd = ["ssh", REMOTE_HOST, f'sqlite3 -header -csv "{db_path}" "{sql}"']
    else:
        cmd = ["sqlite3", "-header", "-csv", db_path, sql]
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    if res.returncode != 0:
        raise RuntimeError(
            f"SQL failed on {db_path}: {res.stderr.strip()}\nSQL: {sql}"
        )
    out = res.stdout.strip()
    if not out:
        return []
    return list(csv.DictReader(io.StringIO(out)))


def _sql_scalar(db_path: str, sql: str) -> str:
    rows = _run_sql(db_path, sql)
    if not rows:
        return "0"
    return next(iter(rows[0].values()))


# ---------------------------------------------------------------------------
# Step 1: commit filtering funnel
# ---------------------------------------------------------------------------


def analyze_step1() -> dict[str, str]:
    print("  Querying step1_commits...")
    total = _int(_sql_scalar(
        ACTIVE_PIPELINE_DB,
        f"SELECT COUNT(*) FROM step1_commits WHERE source_name='{SOURCE_NAME}'",
    ))
    retained = _int(_sql_scalar(
        ACTIVE_PIPELINE_DB,
        f"SELECT COUNT(*) FROM step1_commits "
        f"WHERE source_name='{SOURCE_NAME}' AND excluded=0",
    ))
    rows = _run_sql(
        ACTIVE_PIPELINE_DB,
        f"SELECT exclusion_reason, COUNT(*) AS cnt FROM step1_commits "
        f"WHERE source_name='{SOURCE_NAME}' AND excluded=1 "
        f"GROUP BY exclusion_reason",
    )

    excl_branches = excl_pre_v3 = excl_bot = excl_no_mo = 0
    for r in rows:
        reason = (r.get("exclusion_reason") or "").lower()
        cnt = int(r["cnt"])
        if "excluded branch" in reason:
            excl_branches += cnt
        elif "before tag" in reason:
            excl_pre_v3 += cnt
        elif "no .mo files" in reason:
            excl_no_mo += cnt
        elif any(k in reason for k in (
            "bot", "commit message matches",
            "author name contains", "author email contains",
        )):
            excl_bot += cnt

    return {
        "MbFilterInputCommits":   _fmt_int(total),
        "MbFilterExclBranches":   _fmt_int(excl_branches),
        "MbFilterAfterBranches":  _fmt_int(total - excl_branches),
        "MbFilterExclPreVThree":  _fmt_int(excl_pre_v3),
        "MbFilterAfterPreVThree": _fmt_int(total - excl_branches - excl_pre_v3),
        "MbFilterExclBot":        _fmt_int(excl_bot),
        "MbFilterAfterBot":       _fmt_int(total - excl_branches - excl_pre_v3 - excl_bot),
        "MbFilterExclNoMo":       _fmt_int(excl_no_mo),
        "MbFilterRetained":       _fmt_int(retained),
        "MbFilterRetainedPct":    f"{_pct(retained, total):.1f}",
    }


# ---------------------------------------------------------------------------
# Step 2: class enumeration
# ---------------------------------------------------------------------------


def analyze_step2() -> tuple[dict[str, str], list[dict[str, str]]]:
    print("  Querying step2_classes (summary)...")
    s = _run_sql(
        ACTIVE_STEP2_DB,
        f"SELECT COUNT(*) AS total_rows, "
        f"COUNT(DISTINCT class_name) AS unique_classes, "
        f"SUM(CASE WHEN is_experiment=1 THEN 1 ELSE 0 END) AS exp_rows, "
        f"SUM(CASE WHEN is_experiment=0 THEN 1 ELSE 0 END) AS nonexp_rows "
        f"FROM step2_classes WHERE source_name='{SOURCE_NAME}'",
    )[0]
    total_rows = _int(s["total_rows"])
    unique_classes = _int(s["unique_classes"])
    exp_rows = _int(s["exp_rows"])
    nonexp_rows = _int(s["nonexp_rows"])

    print("  Querying per-commit breakdown (may take a while)...")
    per_commit = _run_sql(
        ACTIVE_STEP2_DB,
        f"SELECT commit_hash, COUNT(*) AS total_classes, "
        f"SUM(CASE WHEN is_experiment=1 THEN 1 ELSE 0 END) AS experiment_classes "
        f"FROM step2_classes WHERE source_name='{SOURCE_NAME}' "
        f"GROUP BY commit_hash",
        timeout=600,
    )
    totals = [_int(r["total_classes"]) for r in per_commit]
    experiments = [_int(r["experiment_classes"]) for r in per_commit]
    ratios = [e / t if t else 0.0 for t, e in zip(totals, experiments)]

    values = {
        "MbListDistinctClassNames":     _fmt_int(unique_classes),
        "MbListAllClassVersions":       _fmt_int(total_rows),
        "MbListNonExperimentVersions":  _fmt_int(nonexp_rows),
        "MbListNonExperimentPct":       f"{_pct(nonexp_rows, total_rows):.1f}",
        "MbListExperimentVersions":     _fmt_int(exp_rows),
        "MbListExperimentPct":          f"{_pct(exp_rows, total_rows):.1f}",
        "MbListMaxExperimentPerCommit": str(max(experiments)) if experiments else "0",
        "MbGrowthAllClassMean":         _fmt_int(round(mean(totals))) if totals else "0",
        "MbGrowthExperimentMean":       str(round(mean(experiments))) if experiments else "0",
        "MbGrowthExperimentRatioMean":  f"{mean(ratios) * 100:.1f}" if ratios else "0",
    }
    return values, per_commit


# ---------------------------------------------------------------------------
# Step 3: canonicalisation
# ---------------------------------------------------------------------------


def _count_step2_failed_commits() -> int:
    """Count Step-1-retained commits with zero rows in step2_classes.

    These are commits that Step 2 *walked* (its progress bar ticked) but for
    which class enumeration produced no rows -- typically because
    ``git checkout`` failed on a historical revision, ``loadFile`` of the
    MSL package failed under the current OMC, or ``getClassNames`` returned
    empty. They are commit-level Step-2 load failures and would otherwise be
    invisible to the report (they don't show up in step2_classes, step3_classes,
    or step3_failures).

    We keep them as a *separate* count (in commits) rather than folding into
    ``MbCanonFailures`` (which counts experiment-class versions) so that the
    Step-3 invariants stay clean.
    """
    sql = (
        f"ATTACH '{ACTIVE_STEP2_DB}' AS s2; "
        f"SELECT COUNT(*) FROM step1_commits "
        f"WHERE source_name='{SOURCE_NAME}' AND excluded=0 "
        f"  AND commit_hash NOT IN ("
        f"    SELECT DISTINCT commit_hash FROM s2.step2_classes "
        f"    WHERE source_name='{SOURCE_NAME}'"
        f"  );"
    )
    return _int(_sql_scalar(ACTIVE_PIPELINE_DB, sql))


def _count_commit_level_load_failures() -> int:
    """Count step2 experiment-class rows whose commit produced zero step3 rows.

    Step3 records package-load failures in ``step3_failures`` with an empty
    ``class_name`` and never inserts per-class rows in ``step3_classes`` for
    that commit. We attribute the full per-commit experiment count of each
    such commit to the failure bucket so totals reconcile with
    ``MbListExperimentVersions``.
    """
    sql = (
        f"ATTACH '{ACTIVE_PIPELINE_DB}' AS pl; "
        f"SELECT COALESCE(SUM(cnt), 0) FROM ("
        f"  SELECT commit_hash, COUNT(*) AS cnt "
        f"  FROM step2_classes "
        f"  WHERE source_name='{SOURCE_NAME}' AND is_experiment=1 "
        f"    AND commit_hash NOT IN ("
        f"      SELECT DISTINCT commit_hash FROM pl.step3_classes "
        f"      WHERE source_name='{SOURCE_NAME}'"
        f"    ) "
        f"  GROUP BY commit_hash"
        f");"
    )
    return _int(_sql_scalar(ACTIVE_STEP2_DB, sql))


def analyze_step3(extra_load_failures: int = 0) -> dict[str, str]:
    print("  Querying step3_classes...")
    s = _run_sql(
        ACTIVE_PIPELINE_DB,
        f"SELECT SUM(CASE WHEN canonical_produced=1 THEN 1 ELSE 0 END) AS produced, "
        f"SUM(CASE WHEN canonical_produced=0 THEN 1 ELSE 0 END) AS failed "
        f"FROM step3_classes WHERE source_name='{SOURCE_NAME}'",
    )[0]
    produced = _int(s["produced"])
    failures = _int(s["failed"]) + extra_load_failures
    processed = produced + failures

    commits_with_exp = _int(_sql_scalar(
        ACTIVE_STEP2_DB,
        f"SELECT COUNT(DISTINCT commit_hash) FROM step2_classes "
        f"WHERE source_name='{SOURCE_NAME}' AND is_experiment=1",
    ))
    total_retained = _int(_sql_scalar(
        ACTIVE_PIPELINE_DB,
        f"SELECT COUNT(*) FROM step1_commits "
        f"WHERE source_name='{SOURCE_NAME}' AND excluded=0",
    ))

    return {
        "MbCanonCommitsWithExperiment":    _fmt_int(commits_with_exp),
        "MbCanonCommitsWithExperimentPct": f"{_pct(commits_with_exp, total_retained):.1f}",
        "MbCanonProducedVersions":         _fmt_int(produced),
        "MbCanonProducedPct":              f"{_pct(produced, processed):.1f}",
        "MbCanonFailures":                 _fmt_int(failures),
        "MbCanonFailuresPct":              f"{_pct(failures, processed):.1f}",
    }


# ---------------------------------------------------------------------------
# Failure analysis (categorise step3_classes error messages)
# ---------------------------------------------------------------------------

FAILURE_PATTERNS: list[tuple[str, str]] = [
    (r"(?i)loadFile|loadModel|could not (load|open)|package.*not found|failed to load",
     "Package load failure"),
    (r"(?i)extends.*not found|base.?class.*not|could not find.*base|unknown base",
     "Missing base class"),
    (r"(?i)class.*not found|not found in scope|could not find class|unknown class|lookup.*failed",
     "Missing referenced class"),
    (r"(?i)replaceable|redeclare|redeclaration|not replaceable",
     "Replaceable/redeclare conflict"),
    (r"(?i)restriction|operator.?record|illegal.*operator",
     "Operator-record restriction"),
    (r"(?i)type\s+error|type.*mismatch|incompatible.*type",
     "Type mismatch"),
    (r"(?i)savetotalmodel|save.*total.*model|timeout|timed out",
     "Canonicalization timeout"),
    (r"(?i)syntax|parse\s*error|unexpected token",
     "Syntax error"),
]

# Categories that map to LaTeX macros referenced in body.tex.
FAILURE_CATEGORY_VARS: dict[str, tuple[str, str]] = {
    "Operator-record restriction":    ("MbFailOperatorRestriction",   "MbFailOperatorRestrictionPct"),
    "Missing referenced class":       ("MbFailMissingClass",          "MbFailMissingClassPct"),
    "Replaceable/redeclare conflict": ("MbFailRedeclare",             "MbFailRedeclarePct"),
    "Missing base class":             ("MbFailMissingBase",           "MbFailMissingBasePct"),
    "Canonicalization timeout":       ("MbFailTimeout",               "MbFailTimeoutPct"),
    "Package load failure":           ("MbFailPackageLoad",           "MbFailPackageLoadPct"),
}


def analyze_failures(extra_load_failures: int = 0) -> tuple[dict[str, int], int]:
    print("  Querying failure error messages...")
    rows = _run_sql(
        ACTIVE_PIPELINE_DB,
        f"SELECT error_message FROM step3_classes "
        f"WHERE source_name='{SOURCE_NAME}' AND canonical_produced=0 "
        f"AND error_message!=''",
        timeout=600,
    )
    total = len(rows)
    categories: Counter = Counter()
    for r in rows:
        msg = (r.get("error_message") or "").strip()
        if not msg:
            categories["Empty error / unknown"] += 1
            continue
        for pattern, label in FAILURE_PATTERNS:
            if re.search(pattern, msg):
                categories[label] += 1
                break
        else:
            categories["Other"] += 1

    if extra_load_failures:
        categories["Package load failure"] += extra_load_failures
        total += extra_load_failures
    return dict(categories.most_common()), total


# ---------------------------------------------------------------------------
# On-disk artifact sizes
# ---------------------------------------------------------------------------


def get_artifact_sizes() -> dict[str, str]:
    if USE_REMOTE:
        targets = {
            "MbStorePipelineDbSize":   f"{REMOTE_BASE}/dataset/pipeline.db",
            "MbStoreClassEnumDbSize":  f"{REMOTE_BASE}/dataset/step2_classes.db",
            "MbStoreCanonicalDirSize": f"{REMOTE_BASE}/dataset/canonical_models/MSL",
        }
    else:
        targets = {
            "MbStorePipelineDbSize":   PIPELINE_DB_LOCAL,
            "MbStoreClassEnumDbSize":  STEP2_DB_LOCAL,
            "MbStoreCanonicalDirSize": CANONICAL_DIR_LOCAL,
        }
    out: dict[str, str] = {}
    for var, path in targets.items():
        try:
            if USE_REMOTE:
                res = subprocess.run(
                    ["ssh", REMOTE_HOST, f'du -sh "{path}" | cut -f1'],
                    capture_output=True, text=True, timeout=120,
                )
            else:
                res = subprocess.run(
                    f'du -sh "{path}" | cut -f1',
                    shell=True, capture_output=True, text=True, timeout=120,
                )
            if res.returncode != 0:
                print(f"[WARN] du failed for {var}: {res.stderr.strip()}")
                continue
            m = re.match(r"([\d.]+)([KMGT]?)", res.stdout.strip())
            if not m:
                continue
            num, unit = m.groups()
            unit_map = {"K": "KB", "M": "MB", "G": "GB", "T": "TB", "": "B"}
            out[var] = num + r"\," + unit_map[unit]
        except Exception as e:
            print(f"[WARN] Could not measure {var}: {e}")
    return out


# ---------------------------------------------------------------------------
# Step 2 timeline figure (papers/SAM2026/figs/step2_classes_timeline.png)
# ---------------------------------------------------------------------------


def _get_commit_dates(commit_hashes: list[str]) -> dict[str, str]:
    repo_path = LOCAL_SOURCE_DIR / SOURCE_NAME
    if not repo_path.exists():
        print(f"[WARN] Local repo not found at {repo_path}, skipping date resolution")
        return {}
    try:
        import git as gitpython  # type: ignore
    except ImportError:
        print("[WARN] gitpython not installed, skipping date resolution")
        return {}
    try:
        repo = gitpython.Repo(repo_path)
    except Exception as e:
        print(f"[WARN] Cannot open repo: {e}")
        return {}
    wanted = set(commit_hashes)
    dates: dict[str, str] = {}
    for c in repo.iter_commits("--all", max_count=50_000):
        if c.hexsha in wanted:
            dates[c.hexsha] = datetime.fromtimestamp(
                c.committed_date, tz=timezone.utc,
            ).strftime("%Y-%m-%d")
            wanted.discard(c.hexsha)
            if not wanted:
                break
    return dates


def plot_step2_timeline(per_commit_rows: list[dict[str, str]],
                        commit_hashes: list[str]) -> None:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import numpy as np
    except ImportError:
        print("[WARN] matplotlib/numpy not installed, skipping figure.")
        return

    dates = _get_commit_dates(commit_hashes)
    if len(dates) < 10:
        print(f"[WARN] Only {len(dates)} commit dates resolved, skipping figure.")
        return

    series = []
    for r in per_commit_rows:
        d = dates.get(r["commit_hash"])
        if d:
            series.append((d, _int(r["total_classes"]), _int(r["experiment_classes"])))
    series.sort(key=lambda x: x[0])
    if len(series) < 10:
        print("[WARN] Insufficient time-series data, skipping figure.")
        return

    plot_dates = [datetime.strptime(d, "%Y-%m-%d") for d, _, _ in series]
    totals = [t for _, t, _ in series]
    experiments = [e for _, _, e in series]

    fig, (ax_top, ax_bot) = plt.subplots(
        2, 1, figsize=(7, 4.5), dpi=160, sharex=True,
        gridspec_kw={"hspace": 0.15},
    )
    window = min(50, len(totals) // 5) if len(totals) > 10 else 1
    kernel = np.ones(window) / window if window > 1 else None
    offset = window // 2

    ax_top.scatter(plot_dates, totals, s=2, alpha=0.25, color="#1f77b4")
    if kernel is not None:
        smooth = np.convolve(totals, kernel, mode="valid")
        ax_top.plot(plot_dates[offset: offset + len(smooth)],
                    smooth, color="#1f77b4", linewidth=1.5)
    ax_top.axhline(mean(totals), color="#1f77b4", linestyle="--",
                   linewidth=0.8, alpha=0.6)
    ax_top.set_ylabel("All classes", fontsize=10)
    ax_top.grid(True, alpha=0.3)
    ax_top.set_title("MSL class population per processed commit", fontsize=10)

    ax_bot.scatter(plot_dates, experiments, s=2, alpha=0.25, color="#ff7f0e")
    if kernel is not None:
        smooth_e = np.convolve(experiments, kernel, mode="valid")
        ax_bot.plot(plot_dates[offset: offset + len(smooth_e)],
                    smooth_e, color="#ff7f0e", linewidth=1.5)
    ax_bot.axhline(mean(experiments), color="#ff7f0e", linestyle="--",
                   linewidth=0.8, alpha=0.6)
    ax_bot.set_ylabel("Simulation-eligible classes", fontsize=10)
    ax_bot.set_xlabel("Commit date")
    ax_bot.grid(True, alpha=0.3)
    ax_top.yaxis.set_label_coords(-0.09, 0.5)
    ax_bot.yaxis.set_label_coords(-0.09, 0.5)

    fig.autofmt_xdate()
    fig.tight_layout()
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    out_path = FIG_DIR / "step2_classes_timeline.png"
    fig.savefig(out_path, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved {out_path}")


# ---------------------------------------------------------------------------
# variables.tex update (in-place rewriting of \newcommand values)
# ---------------------------------------------------------------------------

_NEWCOMMAND_RE = re.compile(r"^(\s*\\newcommand\{\\)([A-Za-z]+)\}\{")


def _parse_newcommand(line: str):
    m = _NEWCOMMAND_RE.match(line)
    if not m:
        return None
    prefix, name = m.group(1), m.group(2)
    i, depth = m.end(), 1
    while i < len(line) and depth > 0:
        if line[i] == "{":
            depth += 1
        elif line[i] == "}":
            depth -= 1
        i += 1
    if depth != 0:
        return None
    return prefix, name, line[m.end(): i - 1], line[i - 1:]


def update_variables_tex(values: dict[str, str]) -> tuple[int, int, set[str]]:
    """Update values in ``variables.tex`` in place.

    Returns ``(macro_count, updated_count, defined_macros)``. Aliased
    macros (whose value starts with ``\\``) are skipped because their
    value is another macro, not a literal.
    """
    text = VARIABLES_TEX.read_text(encoding="utf-8")
    lines = text.splitlines()
    new_lines: list[str] = []
    defined: set[str] = set()
    updated = 0

    for line in lines:
        parsed = _parse_newcommand(line)
        if parsed is None:
            new_lines.append(line)
            continue
        prefix, name, current, suffix = parsed
        defined.add(name)
        new_value = values.get(name)
        # Skip alias-style definitions ("\MbFoo") -- don't overwrite.
        if new_value is not None and not current.startswith("\\") \
                and new_value != current:
            new_lines.append(prefix + name + "}{" + new_value + suffix)
            updated += 1
        else:
            new_lines.append(line)

    VARIABLES_TEX.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
    return len(defined), updated, defined


def _get_pilot_settings() -> dict[str, str]:
    """Read Step-3 pilot-mode configuration from ``run_settings``.

    Returns a mapping like ``{"PILOT_ENABLED": "1", ...}``. Empty when
    the table has no Step-3 rows (older runs).
    """
    try:
        rows = _run_sql(
            ACTIVE_PIPELINE_DB,
            "SELECT key, value FROM run_settings WHERE pipeline_step_number=3",
        )
    except Exception:
        return {}
    return {r["key"]: r["value"] for r in rows}


def _get_step3_commit_progress() -> dict[str, int]:
    try:
        rows = _run_sql(
            ACTIVE_PIPELINE_DB,
            f"SELECT status, COUNT(*) AS cnt FROM step3_commit_progress "
            f"WHERE source_name='{SOURCE_NAME}' GROUP BY status",
        )
    except Exception:
        return {}
    return {r["status"]: int(r["cnt"]) for r in rows}


# ---------------------------------------------------------------------------
# Sanity checks
# ---------------------------------------------------------------------------


def _vi(d: dict[str, str], k: str) -> int:
    raw = d.get(k, "0").replace("{,}", "").replace(",", "")
    try:
        return int(raw)
    except ValueError:
        return 0


def run_sanity_checks(v: dict[str, str], categories: dict[str, int],
                      extra_load: int, step2_failed_commits: int = 0,
                      pilot: dict[str, str] | None = None,
                      step3_progress: dict[str, int] | None = None) -> int:
    fails: list[str] = []
    pilot = pilot or {}
    step3_progress = step3_progress or {}
    pilot_enabled = pilot.get("PILOT_ENABLED", "0") in {"1", "true", "True"}

    def check(label: str, lhs: int, rhs: int) -> None:
        ok = lhs == rhs
        marker = "OK  " if ok else "FAIL"
        diff = "" if ok else f"  (diff={lhs - rhs:+,})"
        print(f"  [{marker}] {label}: {lhs:,} vs {rhs:,}{diff}")
        if not ok:
            fails.append(label)

    in_c = _vi(v, "MbFilterInputCommits")
    excl = (_vi(v, "MbFilterExclBranches") + _vi(v, "MbFilterExclPreVThree")
            + _vi(v, "MbFilterExclBot") + _vi(v, "MbFilterExclNoMo"))
    check("Step1: retained + excluded == input",
          _vi(v, "MbFilterRetained") + excl, in_c)

    # Step1-retained == commits that actually produced step2_classes rows + step2 commit-level failures
    retained = _vi(v, "MbFilterRetained")
    commits_with_classes = retained - step2_failed_commits  # by definition; the check below verifies
    check("Step2: commits-with-classes + commit-level load failures == Step1 retained",
          commits_with_classes + step2_failed_commits, retained)
    if step2_failed_commits:
        print(f"  [INFO] Step-2 commit-level load failures: {step2_failed_commits:,} "
              f"(commits in step1_commits.excluded=0 with no rows in step2_classes; "
              f"NOT folded into MbCanonFailures because units differ -- commits vs. class versions)")

    all_v = _vi(v, "MbListAllClassVersions")
    exp_v = _vi(v, "MbListExperimentVersions")
    check("Step2: experiment + non-experiment == all",
          exp_v + _vi(v, "MbListNonExperimentVersions"), all_v)

    if pilot_enabled:
        # Step 3 was run in *pilot* mode: it processes only a bounded
        # sample of experiment classes per commit (see run_settings for
        # PILOT_* keys). The full-population invariant
        # ``produced + failures == MbListExperimentVersions`` therefore
        # does NOT apply. Instead we verify that every commit Step 3
        # was supposed to walk finished successfully.
        complete = step3_progress.get("complete", 0)
        total_progress = sum(step3_progress.values())
        print("  [INFO] Step 3 was run in PILOT mode "
              f"({', '.join(f'{k}={v!r}' for k, v in sorted(pilot.items()))}); "
              "full-population Step-3 invariant is skipped.")
        check("Step3 (pilot): all walked commits complete",
              complete, total_progress)
        check("Step3 (pilot): walked commits == Step1 retained",
              total_progress, retained)
    else:
        check("Step3: produced + failures == experiment versions",
              _vi(v, "MbCanonProducedVersions") + _vi(v, "MbCanonFailures"), exp_v)

    cat_sum = sum(categories.values())
    check("Failure categories sum == MbCanonFailures",
          cat_sum, _vi(v, "MbCanonFailures"))

    pkg_load = categories.get("Package load failure", 0)
    if extra_load and pkg_load < extra_load:
        fails.append("Package-load category < commit-level load failures")
        print(f"  [FAIL] Package-load category ({pkg_load:,}) "
              f"< folded-in commit-level failures ({extra_load:,})")
    else:
        print(f"  [OK  ] Package-load category includes folded-in "
              f"commit-level failures ({extra_load:,})")

    return len(fails)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def _is_figure_only(argv: list[str]) -> bool:
    return "--figure-only" in argv


def _is_pilot_allowed(argv: list[str]) -> bool:
    """Explicit opt-in required to publish pilot-run numbers."""
    return "--allow-pilot" in argv


def _abort_if_pilot(argv: list[str]) -> dict[str, str]:
    """Read Step-3 pilot settings and abort unless ``--allow-pilot``.

    Returns the settings dict on success. Never returns when aborting.
    """
    pilot = _get_pilot_settings()
    enabled = pilot.get("PILOT_ENABLED", "0") in {"1", "true", "True"}
    if not enabled:
        return pilot
    if _is_pilot_allowed(argv):
        print("[WARN] Step 3 was run in PILOT mode -- proceeding because "
              "--allow-pilot was given.")
        for k, v in sorted(pilot.items()):
            print(f"         {k} = {v!r}")
        return pilot
    print("=" * 60)
    print("  ABORT: Step 3 was run in PILOT mode.")
    print("=" * 60)
    print("  Pilot mode canonicalises only a bounded sample of")
    print("  experiment classes per commit, so the resulting Step-3")
    print("  numbers are NOT representative of the full population.")
    print("  variables.tex and figures were NOT modified.")
    print()
    print("  run_settings (pipeline_step_number=3):")
    for k, v in sorted(pilot.items()):
        print(f"    {k} = {v!r}")
    print()
    print("  To publish pilot numbers anyway, re-run with --allow-pilot.")
    print("  To publish full numbers, re-run Step 3 with PILOT_ENABLED=0.")
    sys.exit(2)


def main() -> None:
    figure_only = _is_figure_only(sys.argv[1:])

    print("=" * 60)
    print("  SAM2026 Paper -- Report Generator (MSL only)")
    print("=" * 60)
    if USE_REMOTE:
        print(f"  Mode:        remote (ssh {REMOTE_HOST})")
        print(f"  Remote base: {REMOTE_BASE}")
    else:
        print("  Mode:        local")
        print(f"  Pipeline DB: {PIPELINE_DB_LOCAL}")
        print(f"  Step2 DB:    {STEP2_DB_LOCAL}")
    print(f"  variables.tex: {VARIABLES_TEX}")
    print()

    # Refuse to update anything with pilot-run data unless opted in.
    pilot = _abort_if_pilot(sys.argv[1:])

    if figure_only:
        print("[FIGS] Figure-only mode: regenerating step2 timeline...")
        _, per_commit = analyze_step2()
        plot_step2_timeline(per_commit, [r["commit_hash"] for r in per_commit])
        print("\nDone.")
        return

    values: dict[str, str] = dict(STATIC_VALUES)

    print("[STEP 1] Commit filtering...")
    values.update(analyze_step1())
    print(f"         Retained: {values['MbFilterRetained']}")

    print("\n[STEP 2] Class enumeration...")
    step2_vals, per_commit = analyze_step2()
    values.update(step2_vals)
    print(f"         Experiment versions: {step2_vals['MbListExperimentVersions']}")

    step2_failed_commits = _count_step2_failed_commits()
    print(f"         Step-2 commit-level load failures "
          f"(retained by Step 1, no step2_classes rows): {step2_failed_commits:,}")

    print("\n[STEP 3] Canonicalisation...")
    extra_load = _count_commit_level_load_failures()
    print(f"         Commit-level package-load failures (folded in): {extra_load}")
    values.update(analyze_step3(extra_load_failures=extra_load))
    print(f"         Produced: {values['MbCanonProducedVersions']}, "
          f"Failures: {values['MbCanonFailures']}")

    print("\n[SIZES] Artifact sizes...")
    values.update(get_artifact_sizes())
    for k in ("MbStorePipelineDbSize", "MbStoreClassEnumDbSize",
              "MbStoreCanonicalDirSize"):
        if k in values:
            print(f"         {k} = {values[k]}")

    print("\n[FAILURES] Canonicalisation failure analysis...")
    categories, total_failures = analyze_failures(extra_load_failures=extra_load)
    print(f"         Total: {total_failures}")
    for cat, cnt in sorted(categories.items(), key=lambda x: -x[1]):
        print(f"           {cat:36s} {cnt:>7,}  ({_pct(cnt, total_failures):.1f}%)")
    # Default every failure-category macro to 0 so variables.tex is
    # always fully populated even when a category has no matches.
    for cnt_var, pct_var in FAILURE_CATEGORY_VARS.values():
        values.setdefault(cnt_var, _fmt_int(0))
        values.setdefault(pct_var, "0.0")
    for cat, cnt in categories.items():
        if cat in FAILURE_CATEGORY_VARS:
            cnt_var, pct_var = FAILURE_CATEGORY_VARS[cat]
            values[cnt_var] = _fmt_int(cnt)
            values[pct_var] = f"{_pct(cnt, total_failures):.1f}"

    # Verify we computed exactly the right macros: no surprises, no gaps.
    produced_vars = set(values)
    extra = produced_vars - EXPECTED_VARS
    missing = EXPECTED_VARS - produced_vars
    if extra:
        print(f"\n[WARN] Computed but not expected by body.tex: {sorted(extra)}")
    if missing:
        print(f"\n[WARN] Expected by body.tex but not computed: {sorted(missing)}")

    print("\n[TEX] Updating variables.tex...")
    total, updated, defined = update_variables_tex(values)
    print(f"       Macros in variables.tex: {total}, updated this run: {updated}")
    stray_defined = defined - EXPECTED_VARS - {"MbListProcessedCommits",
                                               "MbCanonInputVersions"}
    if stray_defined:
        print(f"[WARN] Defined but unused in body.tex: {sorted(stray_defined)}")

    print("\n[FIGS] Generating step2 timeline figure...")
    plot_step2_timeline(per_commit, [r["commit_hash"] for r in per_commit])

    print("\n[SANITY] Cross-cutting invariants...")
    pilot = _get_pilot_settings()
    step3_progress = _get_step3_commit_progress()
    nfail = run_sanity_checks(values, categories, extra_load,
                              step2_failed_commits=step2_failed_commits,
                              pilot=pilot, step3_progress=step3_progress)
    print(f"  -> {'all checks passed' if nfail == 0 else f'{nfail} check(s) FAILED'}")

    print("\n" + "=" * 60)
    print("  Done. See papers/SAM2026/variables.tex and figs/.")
    print("=" * 60)


if __name__ == "__main__":
    main()

